INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_FANCONTROL fancontrol)

FIND_PATH(
    FANCONTROL_INCLUDE_DIRS
    NAMES fancontrol/api.h
    HINTS $ENV{FANCONTROL_DIR}/include
        ${PC_FANCONTROL_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    FANCONTROL_LIBRARIES
    NAMES gnuradio-fancontrol
    HINTS $ENV{FANCONTROL_DIR}/lib
        ${PC_FANCONTROL_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FANCONTROL DEFAULT_MSG FANCONTROL_LIBRARIES FANCONTROL_INCLUDE_DIRS)
MARK_AS_ADVANCED(FANCONTROL_LIBRARIES FANCONTROL_INCLUDE_DIRS)

